import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';

const OUT_DIR = path.join(process.cwd(), 'out');
const HEADERS_PATH = path.join(OUT_DIR, '_headers');

function walk(dir) {
  const entries = fs.readdirSync(dir, { withFileTypes: true });
  return entries.flatMap((entry) => {
    const fullPath = path.join(dir, entry.name);
    return entry.isDirectory() ? walk(fullPath) : [fullPath];
  });
}

function hashInlineScript(script) {
  return `'sha256-${crypto.createHash('sha256').update(script).digest('base64')}'`;
}

function getHtmlFiles() {
  return walk(OUT_DIR).filter((file) => file.endsWith('.html'));
}

function getInlineScriptHashes(html) {
  const hashes = new Set();
  const scriptPattern = /<script\b(?![^>]*\bsrc=)[^>]*>([\s\S]*?)<\/script>/gi;

  for (const match of html.matchAll(scriptPattern)) {
    if (match[1].trim()) {
      hashes.add(hashInlineScript(match[1]));
    }
  }

  return [...hashes].sort();
}

function buildCsp(scriptHashes) {
  return [
    "default-src 'self'",
    `script-src 'self' ${scriptHashes.join(' ')} https://*.googletagmanager.com`,
    "style-src 'self' 'unsafe-inline' https://fonts.googleapis.com",
    "font-src 'self' https://fonts.gstatic.com data:",
    "img-src 'self' data: https:",
    "frame-src 'self' https://maps.google.com https://www.google.com",
    "connect-src 'self' https://*.google-analytics.com https://*.analytics.google.com https://*.g.doubleclick.net https://*.googletagmanager.com",
    "base-uri 'self'",
    "form-action 'self' https://formspree.io",
    "frame-ancestors 'self'",
    'upgrade-insecure-requests',
  ].join('; ');
}

function toHeaderPaths(file) {
  const relative = path.relative(OUT_DIR, file).replaceAll(path.sep, '/');
  const withoutHtml = relative.replace(/\.html$/, '');

  if (relative === 'index.html') {
    return ['/', '/index.html'];
  }

  return [`/${withoutHtml}`, `/${relative}`];
}

const htmlFiles = getHtmlFiles();
const pageHeaders = htmlFiles.flatMap((file) => {
  const html = fs.readFileSync(file, 'utf8');
  const hashes = getInlineScriptHashes(html);
  const csp = buildCsp(hashes);

  return toHeaderPaths(file).map((route) => `${route}
  Content-Security-Policy: ${csp}`);
});

const uniqueHashes = new Set();
for (const file of htmlFiles) {
  const html = fs.readFileSync(file, 'utf8');
  for (const hash of getInlineScriptHashes(html)) {
    uniqueHashes.add(hash);
  }
}

const headers = `# ============================================================
# AZ Grand Solutions - generated hardened headers
# Generated by scripts/harden-csp.mjs after next build.
# ============================================================

/*
  Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
  X-Content-Type-Options: nosniff
  X-Frame-Options: SAMEORIGIN
  Referrer-Policy: strict-origin-when-cross-origin
  Permissions-Policy: camera=(), microphone=(), geolocation=(), payment=(), usb=(), magnetometer=(), accelerometer=(), gyroscope=()
  Content-Signal: search=yes, ai-train=no

${pageHeaders.join('\n\n')}

/assets/img/*
  Cache-Control: public, max-age=31536000, immutable

/assets/fonts/*
  Cache-Control: public, max-age=31536000, immutable

/_next/static/*
  Cache-Control: public, max-age=31536000, immutable

/*.html
  Cache-Control: public, max-age=300, must-revalidate
`;

fs.writeFileSync(HEADERS_PATH, headers);
console.log(`Generated strict page-level CSP for ${htmlFiles.length} pages with ${uniqueHashes.size} unique inline script hashes.`);
