import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';

const OUT_DIR = path.join(process.cwd(), 'out');
const HEADERS_PATH = path.join(OUT_DIR, '_headers');
const FUNCTIONS_DIR = path.join(process.cwd(), 'functions');
const MIDDLEWARE_PATH = path.join(FUNCTIONS_DIR, '_middleware.js');

function walk(dir) {
  const entries = fs.readdirSync(dir, { withFileTypes: true });
  return entries.flatMap((entry) => {
    const fullPath = path.join(dir, entry.name);
    return entry.isDirectory() ? walk(fullPath) : [fullPath];
  });
}

function hashInlineScript(script) {
  return `'sha256-${crypto.createHash('sha256').update(script).digest('base64')}'`;
}

function getHtmlFiles() {
  return walk(OUT_DIR).filter((file) => file.endsWith('.html'));
}

function getInlineScriptHashes(html) {
  const hashes = new Set();
  const scriptPattern = /<script\b(?![^>]*\bsrc=)[^>]*>([\s\S]*?)<\/script>/gi;

  for (const match of html.matchAll(scriptPattern)) {
    if (match[1].trim()) {
      hashes.add(hashInlineScript(match[1]));
    }
  }

  return [...hashes].sort();
}

function buildCsp(scriptHashes) {
  return [
    "default-src 'self'",
    `script-src 'self' ${scriptHashes.join(' ')} https://*.googletagmanager.com`,
    "style-src 'self' 'unsafe-inline'",
    "font-src 'self' data:",
    "img-src 'self' data:",
    "frame-src 'self' https://maps.google.com https://www.google.com",
    "connect-src 'self' https://*.google-analytics.com https://*.analytics.google.com https://*.g.doubleclick.net https://*.googletagmanager.com",
    "base-uri 'self'",
    "form-action 'self' https://formspree.io",
    "frame-ancestors 'self'",
    'upgrade-insecure-requests',
  ].join('; ');
}

function toHeaderPaths(file) {
  const relative = path.relative(OUT_DIR, file).replaceAll(path.sep, '/');
  const withoutHtml = relative.replace(/\.html$/, '');

  if (relative === 'index.html') {
    return ['/', '/index.html'];
  }

  return [`/${withoutHtml}`, `/${relative}`];
}

const htmlFiles = getHtmlFiles();
const cspByPath = {};
const uniqueHashes = new Set();
for (const file of htmlFiles) {
  const html = fs.readFileSync(file, 'utf8');
  const hashes = getInlineScriptHashes(html);
  const csp = buildCsp(hashes);

  for (const route of toHeaderPaths(file)) {
    cspByPath[route] = csp;
  }

  for (const hash of hashes) {
    uniqueHashes.add(hash);
  }
}

const headers = `# ============================================================
# AZ Grand Solutions - generated hardened headers
# Generated by scripts/harden-csp.mjs after next build.
# ============================================================

/*
  Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
  X-Content-Type-Options: nosniff
  X-Frame-Options: SAMEORIGIN
  Cross-Origin-Opener-Policy: same-origin
  Cross-Origin-Resource-Policy: same-site
  Referrer-Policy: strict-origin-when-cross-origin
  Permissions-Policy: camera=(), microphone=(), geolocation=(), payment=(), usb=(), magnetometer=(), accelerometer=(), gyroscope=()
  Content-Signal: search=yes, ai-train=no

/assets/img/*
  Cache-Control: public, max-age=31536000, immutable

/assets/fonts/*
  Cache-Control: public, max-age=31536000, immutable

/_next/static/*
  Cache-Control: public, max-age=31536000, immutable

/*.html
  Cache-Control: public, max-age=300, must-revalidate
`;

const middleware = `// Generated by scripts/harden-csp.mjs after next build.
// Do not edit by hand.

const CSP_BY_PATH = ${JSON.stringify(cspByPath, null, 2)};

const SECURITY_HEADERS = {
  'Strict-Transport-Security': 'max-age=31536000; includeSubDomains; preload',
  'X-Content-Type-Options': 'nosniff',
  'X-Frame-Options': 'SAMEORIGIN',
  'Cross-Origin-Opener-Policy': 'same-origin',
  'Cross-Origin-Resource-Policy': 'same-site',
  'Referrer-Policy': 'strict-origin-when-cross-origin',
  'Permissions-Policy': 'camera=(), microphone=(), geolocation=(), payment=(), usb=(), magnetometer=(), accelerometer=(), gyroscope=()',
  'Content-Signal': 'search=yes, ai-train=no',
};

function getCspPath(pathname) {
  if (pathname !== '/' && pathname.endsWith('/')) {
    pathname = pathname.slice(0, -1);
  }

  if (CSP_BY_PATH[pathname]) return pathname;
  if (pathname !== '/' && CSP_BY_PATH[pathname + '.html']) {
    return pathname + '.html';
  }
  return null;
}

export async function onRequest(context) {
  const response = await context.next();
  const headers = new Headers(response.headers);
  const { pathname } = new URL(context.request.url);

  for (const [name, value] of Object.entries(SECURITY_HEADERS)) {
    headers.set(name, value);
  }

  headers.delete('Access-Control-Allow-Origin');

  if (
    pathname.startsWith('/assets/img/') ||
    pathname.startsWith('/assets/fonts/') ||
    pathname.startsWith('/_next/static/')
  ) {
    headers.set('Cache-Control', 'public, max-age=31536000, immutable');
  }

  const cspPath = getCspPath(pathname);
  if (cspPath) {
    headers.set('Content-Security-Policy', CSP_BY_PATH[cspPath]);
  }

  return new Response(response.body, {
    status: response.status,
    statusText: response.statusText,
    headers,
  });
}
`;

fs.writeFileSync(HEADERS_PATH, headers);
fs.mkdirSync(FUNCTIONS_DIR, { recursive: true });
fs.writeFileSync(MIDDLEWARE_PATH, middleware);

console.log(`Generated strict page-level CSP middleware for ${htmlFiles.length} pages with ${uniqueHashes.size} unique inline script hashes.`);
